import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";

import "../globals.css";

// Создание настройки шрифта Inter с поддержкой латиницы
const inter = Inter({ subsets: ["latin"] });

// Метаданные страницы
export const metadata: Metadata = {
  title: "Auth",
  description: "Generated by create next app",
};

// Определение компонента RootLayout
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    // Обертка ClerkProvider, предоставляющая функциональность аутентификации Clerk
    <ClerkProvider
      appearance={{
        baseTheme: dark,
      }}
    >
      <html lang='en'>
        {/* Вывод дочерних компонентов внутри body */}
        <body className={`${inter.className} bg-dark-1`}>{children}</body>
      </html>
    </ClerkProvider>
  );
}

// Импорт React и необходимых типов и компонентов. Мы импортируем библиотеку React для создания React-компонентов, 
// тип Metadata из Next.js для метаданных страницы, компонент Inter из next/font/google для работы со шрифтами, 
// и компоненты ClerkProvider и dark из @clerk/nextjs и @clerk/themes соответственно.

// Определение компонента RootLayout. Мы создаем функциональный компонент RootLayout, который принимает дочерние 
// компоненты (представленные children) в качестве свойства.

// Обертка ClerkProvider. Мы используем ClerkProvider, который предоставляет функциональность аутентификации Clerk. 
// Мы также настраиваем внешний вид (appearance) с темой dark.